service-admin-docker-image-dev:
  extends:
    - .values-service-admin-dev
    - .values-dev-public-service
    - .build-docker-image-dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - $PROJECT_PATH/**/*
        - .gitlab-ci.yml

ui-admin-docker-image-dev:
  extends:
    - .values-ui-admin-dev
    - .values-dev-public-ui
    - .build-docker-image-dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - $PROJECT_PATH/**/*
        - .gitlab-ci.yml